"""
Export all data from local SQLite (warehouse.db) to PostgreSQL-compatible SQL.
Generates production_seed.sql with INSERT ... ON CONFLICT DO NOTHING statements.
"""
import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "warehouse.db")
OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "production_seed.sql")

SKIP_TABLES = {"alembic_version", "sqlite_sequence"}


def get_bool_columns(conn):
    """Find all BOOLEAN columns across all tables."""
    bool_cols = {}
    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
    ).fetchall()
    for (tbl,) in tables:
        cols = conn.execute(f'PRAGMA table_info([{tbl}])').fetchall()
        bools = set()
        for col in cols:
            col_type = (col[2] or "").upper()
            if "BOOL" in col_type:
                bools.add(col[1])
        if bools:
            bool_cols[tbl] = bools
    return bool_cols


def get_conflict_column(conn, table):
    """Find the best column for ON CONFLICT (unique or PK)."""
    indexes = conn.execute(f'PRAGMA index_list([{table}])').fetchall()
    for idx in indexes:
        if idx[2]:  # is_unique
            cols = conn.execute(f'PRAGMA index_info([{idx[1]}])').fetchall()
            if len(cols) == 1:
                return cols[0][2]
    # Fall back to primary key
    pk_cols = conn.execute(f'PRAGMA table_info([{table}])').fetchall()
    for col in pk_cols:
        if col[5] == 1:
            return col[1]
    return "id"


def format_value(val, is_bool=False):
    """Format a Python value as a PostgreSQL literal."""
    if val is None:
        return "NULL"
    if is_bool:
        if isinstance(val, (int, float)):
            return "TRUE" if val else "FALSE"
        if isinstance(val, str):
            return "TRUE" if val.lower() in ("1", "true", "yes") else "FALSE"
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    s = str(val).replace("'", "''")
    return f"'{s}'"


def export():
    conn = sqlite3.connect(DB_PATH)
    bool_cols_map = get_bool_columns(conn)

    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
    ).fetchall()

    total_tables = 0
    total_rows = 0

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("-- Production seed data exported from local SQLite\n")
        f.write("-- Generated by export_to_postgres.py\n")
        f.write("-- Use: psql -U warehouse_user -d warehouse -f production_seed.sql\n\n")

        for (tbl,) in tables:
            if tbl in SKIP_TABLES:
                continue

            pragma = conn.execute(f'PRAGMA table_info([{tbl}])').fetchall()
            col_names = [p[1] for p in pragma]
            bool_set = bool_cols_map.get(tbl, set())
            conflict_col = get_conflict_column(conn, tbl)

            all_rows = conn.execute(f'SELECT * FROM [{tbl}]').fetchall()
            if not all_rows:
                continue

            quoted_cols = ", ".join(f'"{c}"' for c in col_names)

            f.write(f"-- Table: {tbl} ({len(all_rows)} rows)\n")

            for row in all_rows:
                vals = []
                for i, col in enumerate(col_names):
                    vals.append(format_value(row[i], is_bool=(col in bool_set)))
                vals_str = ", ".join(vals)
                f.write(
                    f'INSERT INTO "{tbl}" ({quoted_cols}) '
                    f"VALUES ({vals_str}) "
                    f'ON CONFLICT ("{conflict_col}") DO NOTHING;\n'
                )

            f.write("\n")
            total_tables += 1
            total_rows += len(all_rows)

        # Reset sequences for all tables with serial/identity PKs
        f.write("-- Reset sequences to max(id) + 1\n")
        for (tbl,) in tables:
            if tbl in SKIP_TABLES:
                continue
            pragma = conn.execute(f'PRAGMA table_info([{tbl}])').fetchall()
            for col in pragma:
                if col[5] == 1 and col[1] == "id":
                    f.write(
                        f"SELECT setval(pg_get_serial_sequence('\"{tbl}\"', 'id'), "
                        f"COALESCE((SELECT MAX(id) FROM \"{tbl}\"), 0) + 1, false);\n"
                    )
                    break
        f.write("\n")

    conn.close()
    print(f"Exported {total_tables} tables, {total_rows} rows to {OUTPUT}")
    file_size = os.path.getsize(OUTPUT)
    print(f"File size: {file_size:,} bytes ({file_size/1024:.1f} KB)")


if __name__ == "__main__":
    export()
