// Shared role-based page access map — used by Navigation.js and App.js
// If a page is not listed here, it's accessible to all logged-in users.
export const PAGE_ROLE_MAP = {
  'dashboard':            ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF','SALES_STAFF','DELIVERY_DRIVER','ACCOUNTANT'],
  'products':             ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF','SALES_STAFF','ACCOUNTANT'],
  'stock-receipt':        ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'stock-levels':         ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF','SALES_STAFF'],
  'stock-take':           ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'stock-issue':          ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'stock-alerts':         ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'expiry-tracker':       ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'inventory-dashboard':  ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'barcode-scanner':      ['ADMIN','WAREHOUSE_MANAGER'],
  'fifo-manager':         ['ADMIN','WAREHOUSE_MANAGER'],
  'barcode-labels':       ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'warehouses':           ['ADMIN','WAREHOUSE_MANAGER'],
  'suppliers':            ['ADMIN','WAREHOUSE_MANAGER'],
  'purchase-orders':      ['ADMIN','WAREHOUSE_MANAGER'],
  'purchase-order-detail':['ADMIN','WAREHOUSE_MANAGER'],
  'purchase-invoices':    ['ADMIN','WAREHOUSE_MANAGER','ACCOUNTANT'],
  'landed-costs':         ['ADMIN','WAREHOUSE_MANAGER','ACCOUNTANT'],
  'purchase-returns':     ['ADMIN','WAREHOUSE_MANAGER'],
  'bills':                ['ADMIN','WAREHOUSE_MANAGER','ACCOUNTANT'],
  'customers':            ['ADMIN','SALES_STAFF','ACCOUNTANT'],
  'estimates':            ['ADMIN','SALES_STAFF','WAREHOUSE_MANAGER'],
  'sales-orders':         ['ADMIN','SALES_STAFF','WAREHOUSE_MANAGER'],
  'sales-order-detail':   ['ADMIN','SALES_STAFF','WAREHOUSE_MANAGER'],
  'sales-invoices':       ['ADMIN','SALES_STAFF','ACCOUNTANT'],
  'pricing-rules':        ['ADMIN','SALES_STAFF'],
  'deliveries':           ['ADMIN','SALES_STAFF','WAREHOUSE_MANAGER','DELIVERY_DRIVER'],
  'customer-statement':   ['ADMIN','SALES_STAFF','ACCOUNTANT'],
  'returns-manager':      ['ADMIN','SALES_STAFF','WAREHOUSE_MANAGER','ACCOUNTANT'],
  'collections':          ['ADMIN','SALES_STAFF','WAREHOUSE_MANAGER','ACCOUNTANT'],
  'van-sales':            ['ADMIN','WAREHOUSE_MANAGER'],
  'van-sales-entry':      ['ADMIN','WAREHOUSE_MANAGER'],
  'van-load-sheet':       ['ADMIN','WAREHOUSE_MANAGER'],
  'driver-due-summary':   ['ADMIN','WAREHOUSE_MANAGER','ACCOUNTANT'],
  'driver-dashboard':     ['ADMIN','DELIVERY_DRIVER'],
  'driver-app':           ['ADMIN','DELIVERY_DRIVER'],
  'route-optimizer':      ['ADMIN','DELIVERY_DRIVER','WAREHOUSE_MANAGER'],
  'financial':            ['ADMIN','WAREHOUSE_MANAGER','ACCOUNTANT'],
  'chart-of-accounts':    ['ADMIN','ACCOUNTANT'],
  'money-transfer':       ['ADMIN','ACCOUNTANT'],
  'journal-entries':      ['ADMIN','ACCOUNTANT'],
  'cash-transactions':    ['ADMIN','ACCOUNTANT'],
  'multi-currency':       ['ADMIN','ACCOUNTANT','SALES_STAFF'],
  'reports':              ['ADMIN','WAREHOUSE_MANAGER','SALES_STAFF','ACCOUNTANT'],
  'vat-return':           ['ADMIN','ACCOUNTANT'],
  'bank-recon':           ['ADMIN','ACCOUNTANT'],
  'advance-payments':     ['ADMIN','ACCOUNTANT','SALES_STAFF'],
  'bank-accounts':        ['ADMIN','ACCOUNTANT'],
  'balance-sheet':        ['ADMIN','ACCOUNTANT'],
  'general-ledger':       ['ADMIN','ACCOUNTANT'],
  'vendor-ledger':        ['ADMIN','ACCOUNTANT'],
  'all-sales-report':     ['ADMIN','ACCOUNTANT'],
  'customer-sales-summary':['ADMIN','ACCOUNTANT'],
  'product-sales':        ['ADMIN','ACCOUNTANT'],
  'all-purchases-report': ['ADMIN','ACCOUNTANT'],
  'expense-breakdown':    ['ADMIN','ACCOUNTANT'],
  'sales-tax':            ['ADMIN','ACCOUNTANT'],
  'users':                ['ADMIN'],
  'settings':             ['ADMIN'],
  'notifications':        ['ADMIN','ACCOUNTANT','WAREHOUSE_MANAGER'],
  'messaging':            ['ADMIN'],
  'activity-log':         ['ADMIN'],
  'settings-lookup':      ['ADMIN'],
  'stock-log':            ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'categories':           ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'product-brands':       ['ADMIN'],
  'variations':           ['ADMIN'],
  'damage-items':         ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF'],
  'deleted-items':        ['ADMIN'],
  'admin-master-panel':   ['ADMIN'],
  'label-editor':         ['ADMIN','WAREHOUSE_MANAGER','WAREHOUSE_STAFF','SALES_STAFF','ACCOUNTANT'],
};

export function canAccessPage(page, role) {
  if (!role) return true;
  const allowed = PAGE_ROLE_MAP[page];
  if (!allowed) return true;
  return allowed.some(r => r.toUpperCase() === role.toUpperCase());
}
